# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb59deff64ca5e6bfa0ce248ba1145e3fe8d7b5686d26ed8a003cdd3cd30d7ba11f4ff025a0b9b8f9b79215466dcab0b1b6a2634d6716c5f159f16948657043a

test:
  secret_key_base: 41b27470c7c70c8892b6dce09d8dfde5fa096f8c646ab10e425986e63a3c217d40864d5aba40f7f16cb34546864745fcbed20a95661a69f4f75b47b0dc7be391

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
